version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
    volumes:
      - ./data:/data  # Para persistência de dados se usar H2 em modo arquivo
    depends_on:
      - h2-console

  h2-console:
    image: oscarfonts/h2
    ports:
      - "8082:8082"
    volumes:
      - ./h2-data:/opt/h2-data
    environment:
      - H2_OPTIONS=-web -webAllowOthers -webPort 8082
